name: test

on: 
  push:
    branches: [ "dev-2.0" ]
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.3.1
        with:
          version: stable
      
      - name: Clean Unneeded Submodules
        run: | 
          rm -r src/L2/Superchain/
        id: clean

      - name: Run Forge build
        run: |
          forge --version
          forge soldeer install
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          mkdir -p logs
          forge test -vvv --json > logs/forge-test-log.json || true
        id: test

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        with:
          name: forge-test-log
          path: logs/forge-test-log.json
          overwrite: true
